[[redirects]]
  from = "https://edme.dev/*"
  to = "https://www.edme.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://edme.dev/*"
  to = "http://www.edme.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.edme.dev/*"
  to = "https://www.edme.dev/:splat"
  status = 301
  force = true